# global settings
title: "Line Pouchard Home Page"
url: "https://linepouchard.github.io"
baseurl: "/profile"
theme: "jekyll-theme-cayman"

# build settings
markdown: kramdown
gems:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
